### ISSUE TITLE
kleiner Übersetzungsfehler

### ISSUE THREAD

**Issue by bebehei** [ralfth/git-po-de#4]
Hi,

Zeile 4298 in de.po:
> "Nachdem Sie das getan hast, können Sie Ihre Identität für diesen Commit "
zu
> "Nachdem Sie das getan haben, können Sie Ihre Identität für diesen Commit "
ändern. Vielen Dank.

Trotzdem, sehr gute Arbeit in der deutschen Übersetzung gemacht!

**Comment by ralfth** [comment]
Danke für den Bugreport und den Patch!

http://thread.gmane.org/gmane.comp.version-control.git/263039
